version: "3"
services:
  cams:
    read_only: true
    deploy:
      replicas: 0
      labels:
        - com.df.cron2=true
        - com.df.distribute=true
        - com.df.schedule=0 30 * * * *
      restart_policy:
        condition: none
    image: pinked/camera-synology-lister-mqtt:${DRONE_BUILD_NUMBER}
    environment:
      - SYNOLOGY_USER=${SYNOLOGY_USER}
      - SYNOLOGY_PASS=${SYNOLOGY_PASS}
      - SYNOLOGY_HOST=${SYNOLOGY_HOST}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - TOPIC_PREFIX=${TOPIC_PREFIX}